### This notebook allows the user to evaluate the structure and content of valid XML metadata using the metadataEvaluation Python module. Documentation concepts can be identified for a broad subset of earth science metadata standards. These concepts allow for records to be assessed by many communities conventions for essential discovery metadata.

#### Now let's select some metadata.

In [1]:
#modules to support functions
import pandas
from ipywidgets import *
import ipywidgets as widgets
from IPython.display import display
import metadataEvaluation

os.makedirs('../data/Combined', exist_ok=True)

#functions to identify and label an xml collection for Metadata Evaluation
def OrganizationChoices(organization):
    global Organization
    Organization=organization
    print("Curating Organization", Organization)
    
def CollectionName(collection):
    global Collection
    Collection=collection
    print("Collection is named", Collection)
    
def DialectName(dialect):
    global Dialect
    Dialect=dialect
    print("Collection is written in the", Dialect,"dialect")   
    
def metadataLocation(directory):
    global MetadataLocation
    MetadataLocation=directory
    print("The local directory", MetadataLocation,"contains the metadata for evaluation")    
        
w=interactive(OrganizationChoices, organization='')    
w2=interactive(CollectionName, collection='')
w3=interactive(DialectName, dialect='')
w4=interactive(metadataLocation, directory='')    

display(w)
display(w2)
display(w3)
display(w4)

Evaluate the collection and assign the results to a variable

In [2]:
EvaluatedMetadataDF=metadataEvaluation.XMLeval(MetadataLocation, Organization, Collection, Dialect)
EvaluatedMetadataDF

,Concept,Content,Record,XPath
0,Abstract,"Nanomolar concentrations of PO4, NO3, NO2 (sur...",dataset_3470.xml,/gmi:MI_Metadata/gmd:identificationInfo/gmd:MD...
1,Acknowledgement,Funding provided by NSF Ocean Sciences (NSF OC...,dataset_3470.xml,/gmi:MI_Metadata/gmd:identificationInfo/gmd:MD...
2,Acknowledgement,Funding provided by NSF Ocean Sciences (NSF OC...,dataset_3470.xml,/gmi:MI_Metadata/gmd:identificationInfo/gmd:MD...
3,Address,WHOI MS#36,dataset_3470.xml,/gmi:MI_Metadata/gmd:contact/gmd:CI_Responsibl...
4,Address,"Department of Ocean, Earth, and Atmospheric Sc...",dataset_3470.xml,/gmi:MI_Metadata/gmd:identificationInfo/gmd:MD...
5,Address,WHOI MS#36,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmd:MD_Featur...
6,Address,WHOI MS#36,dataset_3470.xml,/gmi:MI_Metadata/gmd:distributionInfo/gmd:MD_D...
7,Address,WHOI MS#36,dataset_3470.xml,/gmi:MI_Metadata/gmd:metadataMaintenance/gmd:M...
8,AssociatedDIFs,U.S. GEOTRACES,dataset_3470.xml,/gmi:MI_Metadata/gmd:identificationInfo/gmd:MD...
9,AssociatedDIFs,U.S. GEOTRACES NAT,dataset_3470.xml,/gmi:MI_Metadata/gmd:identificationInfo/gmd:MD...
10,Association,U.S. GEOTRACES http://www.geotraces.org/ U.S. ...,dataset_3470.xml,/gmi:MI_Metadata/gmd:identificationInfo/gmd:MD...
11,Association,U.S. GEOTRACES North Atlantic Transect http://...,dataset_3470.xml,/gmi:MI_Metadata/gmd:identificationInfo/gmd:MD...
12,Attribute Definition,PI-supplied Description: Official cruise ident...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
13,Attribute Definition,PI-supplied Description: date (GMT); General D...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
14,Attribute Definition,PI-supplied Description: time (GMT); General D...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
15,Attribute Definition,PI-supplied Description: Station latitude (Sou...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
16,Attribute Definition,PI-supplied Description: Station longitude (We...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
17,Attribute Definition,PI-supplied Description: Identifying number of...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
18,Attribute Definition,PI-supplied Description: Unique identifiers fo...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
19,Attribute Definition,PI-supplied Description: PO4: phosphate (react...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
20,Attribute Definition,PI-supplied Description: PO4 Data Flag: Sample...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
21,Attribute Definition,PI-supplied Description: NO3: Nitrate = (Nitra...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
22,Attribute Definition,PI-supplied Description: NO3 Data Flag: Sample...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
23,Attribute Definition,PI-supplied Description: NO2: Nitrite; General...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
24,Attribute Definition,PI-supplied Description: NO2 Data Flag: Sample...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
25,Attribute Definition,PI-supplied Description: Remarks; General Desc...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
26,Attribute Definition,PI-supplied Description: Unique identifying nu...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
27,Attribute Definition,PI-supplied Description: Unique identifying nu...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
28,Attribute Definition,PI-supplied Description: Date/Time (UTC) forma...,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
29,Attribute Label,cruise_id,dataset_3470.xml,/gmi:MI_Metadata/gmd:contentInfo/gmi:MI_Covera...
...,...,...,...,...
30318,Unknown,http://lod.bco-dmo.org/id/authority/1.rdf,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30319,Unknown,onRequest,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30320,Unknown,unknown,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30321,Unknown,R/V Knorr,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30322,Unknown,http://lod.bco-dmo.org/id/platform/53994.rdf,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30323,Unknown,316N,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30324,Unknown,onRequest,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30325,Unknown,vessel,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30326,Unknown,http://lod.bco-dmo.org/id/platform/53994.rdf,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30327,Unknown,R/V Knorr,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30328,Unknown,onRequest,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30329,Unknown,unknown,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30330,Unknown,http://www.isotc211.org/2005/resources/Codelis...,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30331,Unknown,completed,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30332,Unknown,KN204-01,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30333,Unknown,http://lod.bco-dmo.org/id/deployment/58786.rdf,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30334,Unknown,Cruise,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30335,Unknown,onRequest,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30336,Unknown,unknown,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30337,Unknown,Dr Edward A. Boyle,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30338,Unknown,http://lod.bco-dmo.org/id/person/50984.rdf,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30339,Unknown,onRequest,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30340,Unknown,Massachusetts Institute of Technology,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30341,Unknown,http://lod.bco-dmo.org/id/affiliation/222.rdf,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30342,Unknown,Affiliation,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30343,Unknown,onRequest,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30344,Unknown,http://bcodata.whoi.edu/US_GEOTRACES/AtlanticS...,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30345,Unknown,Report describing KN204-01,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30346,Unknown,http://www.isotc211.org/2005/resources/Codelis...,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...
30347,Unknown,principalInvestigator,dataset_3696.xml,/gmi:MI_Metadata/gmi:acquisitionInformation/gm...

Choose one of the next two functions to create the first data product. Choose the first if you want a full xpath. If you would like to remove namespaces and simplify any ISO xpaths a bit, choose the second. 

This data product allows you to explore many quantitative and qualitative analyses in a variety of datascience and visualization applications.

This module can go through some quantitative analysis using pandas to create some other data products.

In [ ]:
EvaluatedMetadataDF=metadataEvaluation.fullXPathDataProduct(EvaluatedMetadataDF, Organization, Collection, Dialect)
EvaluatedMetadataDF

In [3]:
EvaluatedMetadataDF=metadataEvaluation.simpleXPathDataProduct(EvaluatedMetadataDF, Organization, Collection, Dialect)
EvaluatedMetadataDF

,Concept,Content,Record,Collection,XPath
0,Abstract,"Nanomolar concentrations of PO4, NO3, NO2 (sur...",dataset_3470.xml,b_b,/identificationInfo/abstract
1,Acknowledgement,Funding provided by NSF Ocean Sciences (NSF OC...,dataset_3470.xml,b_b,/identificationInfo/credit
2,Acknowledgement,Funding provided by NSF Ocean Sciences (NSF OC...,dataset_3470.xml,b_b,/identificationInfo/credit
3,Address,WHOI MS#36,dataset_3470.xml,b_b,/contact/contactInfo/address/deliveryPoint
4,Address,"Department of Ocean, Earth, and Atmospheric Sc...",dataset_3470.xml,b_b,/identificationInfo/pointOfContact/contactInfo...
5,Address,WHOI MS#36,dataset_3470.xml,b_b,/contentInfo/featureCatalogueCitation/citedRes...
6,Address,WHOI MS#36,dataset_3470.xml,b_b,/distributionInfo/distributor/distributorConta...
7,Address,WHOI MS#36,dataset_3470.xml,b_b,/metadataMaintenance/contact/contactInfo/addre...
8,AssociatedDIFs,U.S. GEOTRACES,dataset_3470.xml,b_b,/identificationInfo/aggregationInfo/aggregateD...
9,AssociatedDIFs,U.S. GEOTRACES NAT,dataset_3470.xml,b_b,/identificationInfo/aggregationInfo/aggregateD...
10,Association,U.S. GEOTRACES http://www.geotraces.org/ U.S. ...,dataset_3470.xml,b_b,/identificationInfo/aggregationInfo
11,Association,U.S. GEOTRACES North Atlantic Transect http://...,dataset_3470.xml,b_b,/identificationInfo/aggregationInfo
12,Attribute Definition,PI-supplied Description: Official cruise ident...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
13,Attribute Definition,PI-supplied Description: date (GMT); General D...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
14,Attribute Definition,PI-supplied Description: time (GMT); General D...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
15,Attribute Definition,PI-supplied Description: Station latitude (Sou...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
16,Attribute Definition,PI-supplied Description: Station longitude (We...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
17,Attribute Definition,PI-supplied Description: Identifying number of...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
18,Attribute Definition,PI-supplied Description: Unique identifiers fo...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
19,Attribute Definition,PI-supplied Description: PO4: phosphate (react...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
20,Attribute Definition,PI-supplied Description: PO4 Data Flag: Sample...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
21,Attribute Definition,PI-supplied Description: NO3: Nitrate = (Nitra...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
22,Attribute Definition,PI-supplied Description: NO3 Data Flag: Sample...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
23,Attribute Definition,PI-supplied Description: NO2: Nitrite; General...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
24,Attribute Definition,PI-supplied Description: NO2 Data Flag: Sample...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
25,Attribute Definition,PI-supplied Description: Remarks; General Desc...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
26,Attribute Definition,PI-supplied Description: Unique identifying nu...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
27,Attribute Definition,PI-supplied Description: Unique identifying nu...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
28,Attribute Definition,PI-supplied Description: Date/Time (UTC) forma...,dataset_3470.xml,b_b,/contentInfo/dimension/descriptor
29,Attribute Label,cruise_id,dataset_3470.xml,b_b,/contentInfo/dimension/sequenceIdentifier/Memb...
...,...,...,...,...,...
30318,Unknown,http://lod.bco-dmo.org/id/authority/1.rdf,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/ide...
30319,Unknown,onRequest,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/ide...
30320,Unknown,unknown,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/ide...
30321,Unknown,R/V Knorr,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/ide...
30322,Unknown,http://lod.bco-dmo.org/id/platform/53994.rdf,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/ide...
30323,Unknown,316N,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/ide...
30324,Unknown,onRequest,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/ide...
30325,Unknown,vessel,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/des...
30326,Unknown,http://lod.bco-dmo.org/id/platform/53994.rdf,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/des...
30327,Unknown,R/V Knorr,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/des...
30328,Unknown,onRequest,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/des...
30329,Unknown,unknown,dataset_3696.xml,b_b,/acquisitionInformation/operation/platform/ins...
30330,Unknown,http://www.isotc211.org/2005/resources/Codelis...,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/status/...
30331,Unknown,completed,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/status/...
30332,Unknown,KN204-01,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30333,Unknown,http://lod.bco-dmo.org/id/deployment/58786.rdf,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30334,Unknown,Cruise,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30335,Unknown,onRequest,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30336,Unknown,unknown,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30337,Unknown,Dr Edward A. Boyle,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30338,Unknown,http://lod.bco-dmo.org/id/person/50984.rdf,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30339,Unknown,onRequest,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30340,Unknown,Massachusetts Institute of Technology,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30341,Unknown,http://lod.bco-dmo.org/id/affiliation/222.rdf,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30342,Unknown,Affiliation,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30343,Unknown,onRequest,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30344,Unknown,http://bcodata.whoi.edu/US_GEOTRACES/AtlanticS...,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30345,Unknown,Report describing KN204-01,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30346,Unknown,http://www.isotc211.org/2005/resources/Codelis...,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...
30347,Unknown,principalInvestigator,dataset_3696.xml,b_b,/acquisitionInformation/operation/plan/citatio...

In [4]:
metadataEvaluation.contentNotProvidedtest(EvaluatedMetadataDF, Organization, Collection, Dialect)

No elements contain a variant of 'Not provided' in their content for this collection

Lets build a concept occurrence table

In [5]:
ConceptCountsDF=metadataEvaluation.ConceptCounts(EvaluatedMetadataDF, Organization, Collection, Dialect)
ConceptCountsDF

,Collection,Record,Abstract,Acknowledgement,Address,AssociatedDIFs,Association,Attribute Definition,Attribute Label,Author / Originator,...,Standard Name Vocabulary,Temporal Extent,Theme Keyword,Topic Category,URL,Units,Unknown,VariableType,Web Page,Westernmost Longitude
0,b_b,dataset_3470.xml,1,2,5,2,2,17,17,1,...,5,1,15,1,1,17,477,1,7,1
1,b_b,dataset_3484.xml,1,2,5,2,2,5,5,1,...,5,1,6,1,1,5,352,1,7,1
2,b_b,dataset_3485.xml,1,2,5,2,2,14,14,1,...,4,1,14,1,1,14,429,1,7,1
3,b_b,dataset_3486.xml,1,2,5,2,2,16,16,1,...,4,1,15,1,1,16,455,1,7,1
4,b_b,dataset_3510.xml,1,2,5,2,2,11,11,1,...,5,1,11,1,1,11,408,1,7,1
5,b_b,dataset_3513.xml,1,2,5,2,2,11,11,1,...,4,1,10,1,1,11,395,1,7,1
6,b_b,dataset_3514.xml,1,2,5,2,2,10,10,1,...,4,1,9,1,1,10,385,1,7,1
7,b_b,dataset_3515.xml,1,2,5,2,2,11,11,1,...,4,1,10,1,1,11,395,1,7,1
8,b_b,dataset_3516.xml,1,2,5,2,2,27,27,1,...,5,1,24,1,1,27,584,1,7,1
9,b_b,dataset_3517.xml,1,2,5,2,2,248,249,1,...,5,1,91,1,1,249,"1,992",1,7,1
10,b_b,dataset_3518.xml,1,2,5,2,2,29,29,1,...,5,1,26,1,1,29,605,1,7,1
11,b_b,dataset_3519.xml,1,2,5,2,2,169,169,1,...,5,1,90,1,1,169,"1,523",1,7,1
12,b_b,dataset_3520.xml,1,2,5,2,2,14,14,1,...,5,1,17,1,1,14,464,1,7,1
13,b_b,dataset_3521.xml,1,2,5,2,2,22,22,1,...,5,1,21,1,1,22,537,1,7,1
14,b_b,dataset_3659.xml,1,2,5,2,2,17,17,1,...,4,1,17,1,1,17,464,1,7,1
15,b_b,dataset_3662.xml,1,2,5,2,2,174,174,1,...,5,1,91,1,1,174,"1,535",1,7,1
16,b_b,dataset_3664.xml,1,2,5,2,2,15,15,1,...,5,1,17,1,1,15,472,1,7,1
17,b_b,dataset_3671.xml,1,2,5,2,2,12,12,1,...,5,1,12,1,1,12,417,1,7,1
18,b_b,dataset_3672.xml,1,2,5,2,2,12,12,1,...,4,1,11,1,1,12,404,1,7,1
19,b_b,dataset_3673.xml,1,2,5,2,2,12,12,1,...,5,1,12,1,1,12,417,1,7,1
20,b_b,dataset_3674.xml,1,2,5,2,2,12,12,1,...,4,1,11,1,1,12,404,1,7,1
21,b_b,dataset_3687.xml,1,2,5,2,2,269,270,1,...,5,1,268,1,1,270,"2,246",1,7,0
22,b_b,dataset_3692.xml,1,1,5,2,2,40,40,1,...,5,1,37,1,1,40,725,1,8,1
23,b_b,dataset_3696.xml,1,2,5,2,2,5,5,1,...,5,1,6,1,1,5,344,1,7,1

In [6]:
conceptOccurrenceDF=metadataEvaluation.conceptOccurrence(EvaluatedMetadataDF, Organization, Collection, Dialect)
conceptOccurrenceDF

,Concept,Collection,ConceptCount,RecordCount,AverageOccurrencePerRecord,CollectionOccurrence%
0,Number of Records,b_b,24,24,1.00,100.00%
1,Abstract,b_b,24,24,1.00,100.00%
2,Acknowledgement,b_b,47,24,1.96,100.00%
3,Address,b_b,120,24,5.00,100.00%
4,AssociatedDIFs,b_b,48,24,2.00,100.00%
5,Association,b_b,48,24,2.00,100.00%
6,Attribute Definition,b_b,1172,24,48.83,100.00%
7,Attribute Label,b_b,1174,24,48.92,100.00%
8,Author / Originator,b_b,24,24,1.00,100.00%
9,Bounding Box,b_b,23,23,0.96,95.83%
10,Cited Resource Identifier,b_b,1,1,0.04,4.17%
11,Cited Resource Title,b_b,333,24,13.88,100.00%
12,City,b_b,120,24,5.00,100.00%
13,Contact Instructions,b_b,96,24,4.00,100.00%
14,Country,b_b,120,24,5.00,100.00%
15,Data Quality Scope,b_b,24,24,1.00,100.00%
16,DataType,b_b,356,24,14.83,100.00%
17,DimensionsName,b_b,1174,24,48.92,100.00%
18,Distribution Contact,b_b,24,24,1.00,100.00%
19,Easternmost Longitude,b_b,23,23,0.96,95.83%
20,Email,b_b,120,24,5.00,100.00%
21,Enumerated Domain Value Definition Source,b_b,112,24,4.67,100.00%
22,Fax,b_b,96,24,4.00,100.00%
23,Feature Catalogue Citation,b_b,48,24,2.00,100.00%
24,First Name,b_b,73,24,3.04,100.00%
25,Geographic Description,b_b,24,24,1.00,100.00%
26,Hours of Service,b_b,96,24,4.00,100.00%
27,Instrument,b_b,34,16,1.42,66.67%
28,Instrument Keyword,b_b,34,16,1.42,66.67%
29,Instrument Keyword Vocabulary,b_b,16,16,0.67,66.67%
...,...,...,...,...,...,...
70,Related Resource Citation,b_b,48,24,2.00,100.00%
71,Related Resource Identifier,b_b,110,24,4.58,100.00%
72,Reprocessing Plan Note,b_b,24,24,1.00,100.00%
73,Resource Access Constraints,b_b,48,24,2.00,100.00%
74,Resource Contact,b_b,24,24,1.00,100.00%
75,Resource Creation/Revision Date,b_b,24,24,1.00,100.00%
76,Resource Identifier,b_b,1,1,0.04,4.17%
77,Resource Language,b_b,24,24,1.00,100.00%
78,Resource Lineage,b_b,24,24,1.00,100.00%
79,Resource Long Name,b_b,24,24,1.00,100.00%
80,Resource Status,b_b,24,24,1.00,100.00%
81,Resource Title,b_b,24,24,1.00,100.00%
82,Resource Type,b_b,24,24,1.00,100.00%
83,Resource Update Frequency,b_b,24,24,1.00,100.00%
84,Resource Use Constraints,b_b,24,24,1.00,100.00%
85,Responsibility,b_b,388,24,16.17,100.00%
86,Rights,b_b,24,24,1.00,100.00%
87,Role,b_b,168,24,7.00,100.00%
88,Southernmost Latitude,b_b,23,23,0.96,95.83%
89,Spatial Extent,b_b,23,23,0.96,95.83%
90,Standard Name Vocabulary,b_b,112,24,4.67,100.00%
91,Temporal Extent,b_b,24,24,1.00,100.00%
92,Theme Keyword,b_b,841,24,35.04,100.00%
93,Topic Category,b_b,24,24,1.00,100.00%
94,URL,b_b,24,24,1.00,100.00%
95,Units,b_b,1174,24,48.92,100.00%
96,Unknown,b_b,16429,24,684.54,100.00%
97,VariableType,b_b,24,24,1.00,100.00%
98,Web Page,b_b,169,24,7.04,100.00%
99,Westernmost Longitude,b_b,23,23,0.96,95.83%

In [7]:
xpathOccurrenceDF=metadataEvaluation.xpathOccurrence(EvaluatedMetadataDF, Organization, Collection, Dialect)
xpathOccurrenceDF

,XPath,Collection,XPathCount,RecordCount,AverageOccurrencePerRecord,CollectionOccurrence%
0,Number of Records,b_b,24,24,1.00,100.00%
1,/@schemaLocation,b_b,24,24,1.00,100.00%
2,/acquisitionInformation/instrument,b_b,34,16,1.42,66.67%
3,/acquisitionInformation/instrument/description,b_b,34,16,1.42,66.67%
4,/acquisitionInformation/instrument/identifier/...,b_b,68,16,2.83,66.67%
5,/acquisitionInformation/instrument/identifier/...,b_b,34,16,1.42,66.67%
6,/acquisitionInformation/instrument/identifier/...,b_b,16,16,0.67,66.67%
7,/acquisitionInformation/instrument/identifier/...,b_b,34,16,1.42,66.67%
8,/acquisitionInformation/instrument/identifier/...,b_b,34,16,1.42,66.67%
9,/acquisitionInformation/instrument/type,b_b,68,16,2.83,66.67%
10,/acquisitionInformation/operation/description,b_b,28,24,1.17,100.00%
11,/acquisitionInformation/operation/identifier/code,b_b,28,24,1.17,100.00%
12,/acquisitionInformation/operation/identifier/c...,b_b,28,24,1.17,100.00%
13,/acquisitionInformation/operation/identifier/c...,b_b,24,24,1.00,100.00%
14,/acquisitionInformation/operation/identifier/c...,b_b,28,24,1.17,100.00%
15,/acquisitionInformation/operation/identifier/c...,b_b,24,24,1.00,100.00%
16,/acquisitionInformation/operation/parentOperat...,b_b,24,24,1.00,100.00%
17,/acquisitionInformation/operation/plan/citatio...,b_b,28,24,1.17,100.00%
18,/acquisitionInformation/operation/plan/citatio...,b_b,25,24,1.04,100.00%
19,/acquisitionInformation/operation/plan/citatio...,b_b,50,24,2.08,100.00%
20,/acquisitionInformation/operation/plan/citatio...,b_b,50,24,2.08,100.00%
21,/acquisitionInformation/operation/plan/citatio...,b_b,25,24,1.04,100.00%
22,/acquisitionInformation/operation/plan/citatio...,b_b,100,24,4.17,100.00%
23,/acquisitionInformation/operation/plan/citatio...,b_b,25,24,1.04,100.00%
24,/acquisitionInformation/operation/plan/citatio...,b_b,24,24,1.00,100.00%
25,/acquisitionInformation/operation/plan/citatio...,b_b,25,24,1.04,100.00%
26,/acquisitionInformation/operation/plan/citatio...,b_b,50,24,2.08,100.00%
27,/acquisitionInformation/operation/plan/citatio...,b_b,25,24,1.04,100.00%
28,/acquisitionInformation/operation/plan/citatio...,b_b,24,24,1.00,100.00%
29,/acquisitionInformation/operation/plan/citatio...,b_b,25,24,1.04,100.00%
...,...,...,...,...,...,...
325,/metadataMaintenance/contact/contactInfo,b_b,24,24,1.00,100.00%
326,/metadataMaintenance/contact/contactInfo/addre...,b_b,48,24,2.00,100.00%
327,/metadataMaintenance/contact/contactInfo/addre...,b_b,48,24,2.00,100.00%
328,/metadataMaintenance/contact/contactInfo/addre...,b_b,48,24,2.00,100.00%
329,/metadataMaintenance/contact/contactInfo/addre...,b_b,48,24,2.00,100.00%
330,/metadataMaintenance/contact/contactInfo/addre...,b_b,48,24,2.00,100.00%
331,/metadataMaintenance/contact/contactInfo/addre...,b_b,48,24,2.00,100.00%
332,/metadataMaintenance/contact/contactInfo/conta...,b_b,48,24,2.00,100.00%
333,/metadataMaintenance/contact/contactInfo/hours...,b_b,48,24,2.00,100.00%
334,/metadataMaintenance/contact/contactInfo/onlin...,b_b,24,24,1.00,100.00%
335,/metadataMaintenance/contact/contactInfo/onlin...,b_b,24,24,1.00,100.00%
336,/metadataMaintenance/contact/contactInfo/phone...,b_b,48,24,2.00,100.00%
337,/metadataMaintenance/contact/contactInfo/phone...,b_b,48,24,2.00,100.00%
338,/metadataMaintenance/contact/organisationName,b_b,48,24,2.00,100.00%
339,/metadataMaintenance/contact/organisationName/...,b_b,24,24,1.00,100.00%
340,/metadataMaintenance/contact/organisationName/...,b_b,24,24,1.00,100.00%
341,/metadataMaintenance/contact/organisationName/...,b_b,24,24,1.00,100.00%
342,/metadataMaintenance/contact/role,b_b,48,24,2.00,100.00%
343,/metadataMaintenance/contact/role/@codeList,b_b,24,24,1.00,100.00%
344,/metadataMaintenance/contact/role/@codeListValue,b_b,24,24,1.00,100.00%
345,/metadataMaintenance/contact/role/@codeSpace,b_b,24,24,1.00,100.00%
346,/metadataMaintenance/maintenanceAndUpdateFrequ...,b_b,24,24,1.00,100.00%
347,/metadataMaintenance/maintenanceAndUpdateFrequ...,b_b,24,24,1.00,100.00%
348,/metadataMaintenance/maintenanceAndUpdateFrequ...,b_b,24,24,1.00,100.00%
349,/metadataMaintenance/maintenanceAndUpdateFrequ...,b_b,24,24,1.00,100.00%
350,/metadataMaintenance/maintenanceNote,b_b,48,24,2.00,100.00%
351,/metadataStandardName,b_b,48,24,2.00,100.00%
352,/metadataStandardVersion,b_b,48,24,2.00,100.00%
353,/referenceSystemInfo/@href,b_b,24,24,1.00,100.00%
354,/referenceSystemInfo/@title,b_b,24,24,1.00,100.00%

In [9]:
QuickEDF=metadataEvaluation.QuickEDataProduct(EvaluatedMetadataDF, Organization, Collection, Dialect)
QuickEDF

Record,XPath,dataset_3470.xml,dataset_3484.xml,dataset_3485.xml,dataset_3486.xml,dataset_3510.xml,dataset_3513.xml,dataset_3514.xml,dataset_3515.xml,dataset_3516.xml,...,dataset_3659.xml,dataset_3662.xml,dataset_3664.xml,dataset_3671.xml,dataset_3672.xml,dataset_3673.xml,dataset_3674.xml,dataset_3687.xml,dataset_3692.xml,dataset_3696.xml
0,/@schemaLocation,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,/acquisitionInformation/instrument,1,1,0,0,1,0,0,0,4,...,0,2,3,1,0,1,0,2,3,1
2,/acquisitionInformation/instrument/description,1,1,0,0,1,0,0,0,4,...,0,2,3,1,0,1,0,2,3,1
3,/acquisitionInformation/instrument/identifier/...,2,2,0,0,2,0,0,0,8,...,0,4,6,2,0,2,0,4,6,2
4,/acquisitionInformation/instrument/identifier/...,1,1,0,0,1,0,0,0,4,...,0,2,3,1,0,1,0,2,3,1
5,/acquisitionInformation/instrument/identifier/...,1,1,0,0,1,0,0,0,1,...,0,1,1,1,0,1,0,1,1,1
6,/acquisitionInformation/instrument/identifier/...,1,1,0,0,1,0,0,0,4,...,0,2,3,1,0,1,0,2,3,1
7,/acquisitionInformation/instrument/identifier/...,1,1,0,0,1,0,0,0,4,...,0,2,3,1,0,1,0,2,3,1
8,/acquisitionInformation/instrument/type,2,2,0,0,2,0,0,0,8,...,0,4,6,2,0,2,0,4,6,2
9,/acquisitionInformation/operation/description,2,2,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
10,/acquisitionInformation/operation/identifier/code,2,2,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
11,/acquisitionInformation/operation/identifier/c...,2,2,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
12,/acquisitionInformation/operation/identifier/c...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
13,/acquisitionInformation/operation/identifier/c...,2,2,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
14,/acquisitionInformation/operation/identifier/c...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
15,/acquisitionInformation/operation/parentOperat...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
16,/acquisitionInformation/operation/plan/citatio...,2,2,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
17,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
18,/acquisitionInformation/operation/plan/citatio...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,4,2
19,/acquisitionInformation/operation/plan/citatio...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,4,2
20,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
21,/acquisitionInformation/operation/plan/citatio...,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,8,4
22,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
23,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
24,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
25,/acquisitionInformation/operation/plan/citatio...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,4,2
26,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
27,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
28,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,1
29,/acquisitionInformation/operation/plan/citatio...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,/metadataMaintenance/contact/contactInfo,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
325,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
326,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
327,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
328,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
329,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
330,/metadataMaintenance/contact/contactInfo/addre...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
331,/metadataMaintenance/contact/contactInfo/conta...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
332,/metadataMaintenance/contact/contactInfo/hours...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
333,/metadataMaintenance/contact/contactInfo/onlin...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
334,/metadataMaintenance/contact/contactInfo/onlin...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
335,/metadataMaintenance/contact/contactInfo/phone...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
336,/metadataMaintenance/contact/contactInfo/phone...,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
337,/metadataMaintenance/contact/organisationName,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
338,/metadataMaintenance/contact/organisationName/...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
339,/metadataMaintenance/contact/organisationName/...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
340,/metadataMaintenance/contact/organisationName/...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
341,/metadataMaintenance/contact/role,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
342,/metadataMaintenance/contact/role/@codeList,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
343,/metadataMaintenance/contact/role/@codeListValue,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
344,/metadataMaintenance/contact/role/@codeSpace,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
345,/metadataMaintenance/maintenanceAndUpdateFrequ...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
346,/metadataMaintenance/maintenanceAndUpdateFrequ...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
347,/metadataMaintenance/maintenanceAndUpdateFrequ...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
348,/metadataMaintenance/maintenanceAndUpdateFrequ...,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
349,/metadataMaintenance/maintenanceNote,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
350,/metadataStandardName,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
351,/metadataStandardVersion,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
352,/referenceSystemInfo/@href,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
353,/referenceSystemInfo/@title,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

### Combine different types of evaluated data to compare between collections or observe trends over time

In [10]:
#Create a dropdown that allows multiple selection using command and click with the mouse 
#or arrow keys to select additional individual data tables, or 
#shift with the mouse to select each choice between the two clicked.

#Creates a list of all the paths to evaluated collection data.
EvaluatedMetadata=[]
for dirpath, dirnames, filenames in os.walk("../data"):
    for filename in [f for f in filenames if '.csv' in f]:
        EvaluatedMetadata.extend([os.path.join(dirpath, filename)])

#widget for selecting multiple collections        
w6=widgets.SelectMultiple(
    options=sorted(EvaluatedMetadata),
    value=['../data/Sample/Sample_Sample_Evaluated.csv.gz'],
    #rows=10,
    description='Evaluated Data',
    disabled=False
)
#Show the widget



#widget for naming the file
w5=widgets.Text(
    value='',
    placeholder='Your file name (no spaces)',
    description='Name your File:',
    disabled=False
)

display(w5)
display(w6)

create variables from the widget choices

In [11]:
CollectionComparisons=w6.value
DataDestination=os.path.join('../data/Combined', str(w5.value)+'.csv')

In [12]:
metadataEvaluation.CombineConceptOccurrence(CollectionComparisons,DataDestination)

                                        Concept 2010_EML      b_b
0                                      Abstract   98.00%  100.00%
1                               Acknowledgement        0  100.00%
2                                       Address        0  100.00%
3                                AssociatedDIFs        0  100.00%
4                                   Association        0  100.00%
5                          Attribute Definition   54.00%  100.00%
6                               Attribute Label        0  100.00%
7                                Attribute List   54.00%        0
8                                        Author  100.00%        0
9                           Author / Originator  100.00%  100.00%
10            Author / Originator Email Address   46.00%        0
11               Author / Originator Identifier   55.00%        0
12   Author / Originator World Wide Web Address   53.00%        0
13                                 Bounding Box   97.00%   95.83%
14                    Cited Resource Identifier        0    4.17%
15                         Cited Resource Title        0  100.00%
16                                         City        0  100.00%
17                         Contact Instructions        0  100.00%
18                             Contributor Name   36.00%        0
19                             Contributor Role   36.00%        0
20                                      Country        0  100.00%
21                           Data Quality Scope        0  100.00%
22                                     DataType        0  100.00%
23                               DimensionsName        0  100.00%
24                         Distribution Contact        0  100.00%
25                          Distribution Format   52.00%        0
26                        Easternmost Longitude   97.00%   95.83%
27                                        Email        0  100.00%
28                                     End Time   86.00%        0
29                       Entity Type Definition   38.00%        0
..                                          ...      ...      ...
103                             Resource Status   77.00%  100.00%
104                              Resource Title  100.00%  100.00%
105                               Resource Type        0  100.00%
106                   Resource Update Frequency        0  100.00%
107                    Resource Use Constraints   75.00%  100.00%
108                       Resource on-line Link   82.00%        0
109                              Responsibility        0  100.00%
110                Responsible Party Identifier    4.00%        0
111                                      Rights   75.00%  100.00%
112                                        Role        0  100.00%
113                        Security Constraints   77.00%        0
114                       Southernmost Latitude   97.00%   95.83%
115                              Spatial Extent   97.00%   95.83%
116                    Standard Name Vocabulary        0  100.00%
117                                  Start Time   86.00%        0
118                    Supplemental Information    1.00%        0
119                            Taxonomic Extent    5.00%        0
120                             Temporal Extent   86.00%  100.00%
121                            Temporal Keyword    1.00%        0
122                               Theme Keyword        0  100.00%
123                              Topic Category        0  100.00%
124                                         URL        0  100.00%
125                                       Units        0  100.00%
126                                     Unknown  100.00%  100.00%
127                                VariableType        0  100.00%
128                            Vertical Maximum   12.00%        0
129                            Vertical Minimum   12.00%        0
130                         Vertical Resolution   12.00%        0
131                                    Web Page        0  100.00%
132                       Westernmost Longitude   97.00%   95.83%

[133 rows x 3 columns]

In [13]:
metadataEvaluation.CombineConceptCounts(CollectionComparisons,DataDestination)

                                        Concept  2010_EML  b_b
0                                      Abstract        98   24
1                               Acknowledgement         0   24
2                                       Address         0   24
3                                AssociatedDIFs         0   24
4                                   Association         0   24
5                          Attribute Definition        54   24
6                               Attribute Label         0   24
7                                Attribute List        54    0
8                                        Author       100    0
9                           Author / Originator       100   24
10            Author / Originator Email Address        46    0
11               Author / Originator Identifier        55    0
12   Author / Originator World Wide Web Address        53    0
13                                 Bounding Box        97   23
14                    Cited Resource Identifier         0    1
15                         Cited Resource Title         0   24
16                                         City         0   24
17                         Contact Instructions         0   24
18                             Contributor Name        36    0
19                             Contributor Role        36    0
20                                      Country         0   24
21                           Data Quality Scope         0   24
22                                     DataType         0   24
23                               DimensionsName         0   24
24                         Distribution Contact         0   24
25                          Distribution Format        52    0
26                        Easternmost Longitude        97   23
27                                        Email         0   24
28                                     End Time        86    0
29                       Entity Type Definition        38    0
..                                          ...       ...  ...
103                             Resource Status        77   24
104                              Resource Title       100   24
105                               Resource Type         0   24
106                   Resource Update Frequency         0   24
107                    Resource Use Constraints        75   24
108                       Resource on-line Link        82    0
109                              Responsibility         0   24
110                Responsible Party Identifier         4    0
111                                      Rights        75   24
112                                        Role         0   24
113                        Security Constraints        77    0
114                       Southernmost Latitude        97   23
115                              Spatial Extent        97   23
116                    Standard Name Vocabulary         0   24
117                                  Start Time        86    0
118                    Supplemental Information         1    0
119                            Taxonomic Extent         5    0
120                             Temporal Extent        86   24
121                            Temporal Keyword         1    0
122                               Theme Keyword         0   24
123                              Topic Category         0   24
124                                         URL         0   24
125                                       Units         0   24
126                                     Unknown       100   24
127                                VariableType         0   24
128                            Vertical Maximum        12    0
129                            Vertical Minimum        12    0
130                         Vertical Resolution        12    0
131                                    Web Page         0   24
132                       Westernmost Longitude        97   23

[133 rows x 3 columns]

In [14]:
display(w5)
display(w6)

In [15]:
CollectionComparisons=w6.value
DataDestination=os.path.join('../data/Combined', str(w5.value)+'.csv')

In [16]:
metadataEvaluation.CombineXPathOccurrence(CollectionComparisons,DataDestination)

,XPath,2009_EML,2010_EML,b_b
0,/@schemaLocation,0,0,100.00%
1,/acquisitionInformation/instrument,0,0,66.67%
2,/acquisitionInformation/instrument/description,0,0,66.67%
3,/acquisitionInformation/instrument/identifier/...,0,0,66.67%
4,/acquisitionInformation/instrument/identifier/...,0,0,66.67%
5,/acquisitionInformation/instrument/identifier/...,0,0,66.67%
6,/acquisitionInformation/instrument/identifier/...,0,0,66.67%
7,/acquisitionInformation/instrument/identifier/...,0,0,66.67%
8,/acquisitionInformation/instrument/type,0,0,66.67%
9,/acquisitionInformation/operation/description,0,0,100.00%
10,/acquisitionInformation/operation/identifier/code,0,0,100.00%
11,/acquisitionInformation/operation/identifier/c...,0,0,100.00%
12,/acquisitionInformation/operation/identifier/c...,0,0,100.00%
13,/acquisitionInformation/operation/identifier/c...,0,0,100.00%
14,/acquisitionInformation/operation/identifier/c...,0,0,100.00%
15,/acquisitionInformation/operation/parentOperat...,0,0,100.00%
16,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
17,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
18,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
19,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
20,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
21,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
22,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
23,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
24,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
25,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
26,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
27,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
28,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
29,/acquisitionInformation/operation/plan/citatio...,0,0,100.00%
...,...,...,...,...
944,/metadataMaintenance/contact/contactInfo/addre...,0,0,100.00%
945,/metadataMaintenance/contact/contactInfo/addre...,0,0,100.00%
946,/metadataMaintenance/contact/contactInfo/addre...,0,0,100.00%
947,/metadataMaintenance/contact/contactInfo/addre...,0,0,100.00%
948,/metadataMaintenance/contact/contactInfo/addre...,0,0,100.00%
949,/metadataMaintenance/contact/contactInfo/addre...,0,0,100.00%
950,/metadataMaintenance/contact/contactInfo/conta...,0,0,100.00%
951,/metadataMaintenance/contact/contactInfo/hours...,0,0,100.00%
952,/metadataMaintenance/contact/contactInfo/onlin...,0,0,100.00%
953,/metadataMaintenance/contact/contactInfo/onlin...,0,0,100.00%
954,/metadataMaintenance/contact/contactInfo/phone...,0,0,100.00%
955,/metadataMaintenance/contact/contactInfo/phone...,0,0,100.00%
956,/metadataMaintenance/contact/organisationName,0,0,100.00%
957,/metadataMaintenance/contact/organisationName/...,0,0,100.00%
958,/metadataMaintenance/contact/organisationName/...,0,0,100.00%
959,/metadataMaintenance/contact/organisationName/...,0,0,100.00%
960,/metadataMaintenance/contact/role,0,0,100.00%
961,/metadataMaintenance/contact/role/@codeList,0,0,100.00%
962,/metadataMaintenance/contact/role/@codeListValue,0,0,100.00%
963,/metadataMaintenance/contact/role/@codeSpace,0,0,100.00%
964,/metadataMaintenance/maintenanceAndUpdateFrequ...,0,0,100.00%
965,/metadataMaintenance/maintenanceAndUpdateFrequ...,0,0,100.00%
966,/metadataMaintenance/maintenanceAndUpdateFrequ...,0,0,100.00%
967,/metadataMaintenance/maintenanceAndUpdateFrequ...,0,0,100.00%
968,/metadataMaintenance/maintenanceNote,0,0,100.00%
969,/metadataStandardName,0,0,100.00%
970,/metadataStandardVersion,0,0,100.00%
971,/referenceSystemInfo/@href,0,0,100.00%
972,/referenceSystemInfo/@title,0,0,100.00%
973,Number of Records,100.00%,100.00%,100.00%

In [17]:
metadataEvaluation.CombineXPathCounts(CollectionComparisons,DataDestination)

,XPath,2009_EML,2010_EML,b_b
0,/@schemaLocation,0,0,24
1,/acquisitionInformation/instrument,0,0,16
2,/acquisitionInformation/instrument/description,0,0,16
3,/acquisitionInformation/instrument/identifier/...,0,0,16
4,/acquisitionInformation/instrument/identifier/...,0,0,16
5,/acquisitionInformation/instrument/identifier/...,0,0,16
6,/acquisitionInformation/instrument/identifier/...,0,0,16
7,/acquisitionInformation/instrument/identifier/...,0,0,16
8,/acquisitionInformation/instrument/type,0,0,16
9,/acquisitionInformation/operation/description,0,0,24
10,/acquisitionInformation/operation/identifier/code,0,0,24
11,/acquisitionInformation/operation/identifier/c...,0,0,24
12,/acquisitionInformation/operation/identifier/c...,0,0,24
13,/acquisitionInformation/operation/identifier/c...,0,0,24
14,/acquisitionInformation/operation/identifier/c...,0,0,24
15,/acquisitionInformation/operation/parentOperat...,0,0,24
16,/acquisitionInformation/operation/plan/citatio...,0,0,24
17,/acquisitionInformation/operation/plan/citatio...,0,0,24
18,/acquisitionInformation/operation/plan/citatio...,0,0,24
19,/acquisitionInformation/operation/plan/citatio...,0,0,24
20,/acquisitionInformation/operation/plan/citatio...,0,0,24
21,/acquisitionInformation/operation/plan/citatio...,0,0,24
22,/acquisitionInformation/operation/plan/citatio...,0,0,24
23,/acquisitionInformation/operation/plan/citatio...,0,0,24
24,/acquisitionInformation/operation/plan/citatio...,0,0,24
25,/acquisitionInformation/operation/plan/citatio...,0,0,24
26,/acquisitionInformation/operation/plan/citatio...,0,0,24
27,/acquisitionInformation/operation/plan/citatio...,0,0,24
28,/acquisitionInformation/operation/plan/citatio...,0,0,24
29,/acquisitionInformation/operation/plan/citatio...,0,0,24
...,...,...,...,...
944,/metadataMaintenance/contact/contactInfo/addre...,0,0,24
945,/metadataMaintenance/contact/contactInfo/addre...,0,0,24
946,/metadataMaintenance/contact/contactInfo/addre...,0,0,24
947,/metadataMaintenance/contact/contactInfo/addre...,0,0,24
948,/metadataMaintenance/contact/contactInfo/addre...,0,0,24
949,/metadataMaintenance/contact/contactInfo/addre...,0,0,24
950,/metadataMaintenance/contact/contactInfo/conta...,0,0,24
951,/metadataMaintenance/contact/contactInfo/hours...,0,0,24
952,/metadataMaintenance/contact/contactInfo/onlin...,0,0,24
953,/metadataMaintenance/contact/contactInfo/onlin...,0,0,24
954,/metadataMaintenance/contact/contactInfo/phone...,0,0,24
955,/metadataMaintenance/contact/contactInfo/phone...,0,0,24
956,/metadataMaintenance/contact/organisationName,0,0,24
957,/metadataMaintenance/contact/organisationName/...,0,0,24
958,/metadataMaintenance/contact/organisationName/...,0,0,24
959,/metadataMaintenance/contact/organisationName/...,0,0,24
960,/metadataMaintenance/contact/role,0,0,24
961,/metadataMaintenance/contact/role/@codeList,0,0,24
962,/metadataMaintenance/contact/role/@codeListValue,0,0,24
963,/metadataMaintenance/contact/role/@codeSpace,0,0,24
964,/metadataMaintenance/maintenanceAndUpdateFrequ...,0,0,24
965,/metadataMaintenance/maintenanceAndUpdateFrequ...,0,0,24
966,/metadataMaintenance/maintenanceAndUpdateFrequ...,0,0,24
967,/metadataMaintenance/maintenanceAndUpdateFrequ...,0,0,24
968,/metadataMaintenance/maintenanceNote,0,0,24
969,/metadataStandardName,0,0,24
970,/metadataStandardVersion,0,0,24
971,/referenceSystemInfo/@href,0,0,24
972,/referenceSystemInfo/@title,0,0,24
973,Number of Records,100,100,24